### ISSUE TITLE
#US11 COMO administrador QUIERO poder crear usuarios PARA la aplicación.

### ISSUE THREAD

**Issue by Margarita-Bravo** [TamiSorsaburu/App-Movile#20]
- [x] #36 
La app debe permitir que el administrador pueda crear usuarios del sistema.
- [x] Desarrollar interfaz
- [x] Desarrollar código
- [x] Testear funcionalidad

**Comment by ccrrff2014** [comment]
Crear sección para que un administrador cree un usuario
