### ISSUE TITLE
#US12 COMO usuario QUIERO poder solicitar un turno PARA adquirir los servicios brindados.

### ISSUE THREAD

**Issue by Margarita-Bravo** [TamiSorsaburu/App-Movile#21]
- [ ] #39

**Comment by Margarita-Bravo** [comment]
Task

- [ ] Crear maquetación

**Comment by TamiSorsaburu** [comment]
Hecho.



![Image](https://github.com/TamiSorsaburu/App-Movile/assets/106122755/692aa39c-932d-4d13-b9f5-52ce576eb938)

##

![Image](https://github.com/TamiSorsaburu/App-Movile/assets/106122755/93a2f55d-8b20-4700-afea-b448729a85eb)
