### ISSUE TITLE
#TK14 Crear una sección de turnero

### ISSUE THREAD

**Issue by rominarg** [TamiSorsaburu/App-Movile#39]

**Comment by TamiSorsaburu** [comment]
Hecho.



![Image](https://github.com/TamiSorsaburu/App-Movile/assets/106122755/692aa39c-932d-4d13-b9f5-52ce576eb938)

##

![Image](https://github.com/TamiSorsaburu/App-Movile/assets/106122755/93a2f55d-8b20-4700-afea-b448729a85eb)
