### ISSUE TITLE
#TK26 - Crear sección mécanico

### ISSUE THREAD

**Issue by Margarita-Bravo** [TamiSorsaburu/App-Movile#66]

**Comment by TamiSorsaburu** [comment]
Hecho.



![Image](https://github.com/TamiSorsaburu/App-Movile/assets/106122755/678632ee-d138-4998-b3bf-a7c6c7ea8f0e)




![Image](https://github.com/TamiSorsaburu/App-Movile/assets/106122755/ab44d070-9082-46ed-a71c-f4f7b7b5de0c)
